spring.mail.host=${MAIL_HOST:smtp.sendgrid.net}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:apikey}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST:smtp.sendgrid.net}

app.manager.nombre=${MANAGER_NOMBRE:Manager}
app.manager.contacto=${MANAGER_CONTACTO}

server.port=${PORT:8080}
