spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=bea@bmgmt.es
spring.mail.password=Lenovo1996.-
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.hostinger.com

app.manager.nombre=Beatriz Fernandez BMGMT
app.manager.contacto=bea@bmgmt.es

server.port=${PORT:8080}
