# SMTP Hostinger
spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.hostinger.com

# Manager
app.manager.nombre=${MANAGER_NOMBRE}
app.manager.contacto=${MANAGER_CONTACTO}

# Servidor
server.port=${PORT:8080}
